### ISSUE TITLE
Allow for nested directory structure in elements with the yo polymer:element command

### ISSUE THREAD

**Issue by bostondevin** [yeoman/generator-polymer#110]
I'd like to have a nested element structure to group elements by function / client / etc

I'd like to say something like this:
yo polymer:element grids/basic-grid

It creates the directory just fine and adds it to the elements.html file, but it should also add an index.html file into the grids directory with just the imports that are inside that directory - that way I can import groups of elements like < link rel="import" href="elements/grids" > and have access to everything inside grids. I can add these index files manually, but that's what bower should probably do automagically.

Love what you are doing! Thanks!

**Comment by toadkicker** [comment]
@robdodson I am leaning on the idea of forking the bower registry server. In that we can add some dependency management resolution for import statements. One of the things that I want to get to having is that we can generate the imports based on configuration files. Right now its a bit of a headache when one is missed.

**Comment by robdodson** [comment]
@toadkicker I worked on something similar for [bower and requirejs](https://github.com/yeoman/bower-requirejs). I think the situation with imports can be improved with better tooling (for instance, it'd be nice if my IDE or Chrome Dev tools told me about missing one). Right now we have [a bookmarklet](https://www.polymer-project.org/docs/polymer/debugging.html#unregistered-element-bookmarklet) that will do that, but there could be a lot more done in this space.

**Comment by toadkicker** [comment]
Ok that bookmarklet is useful =) I'll play with it and see what I can come up with. 

As far as this issue goes, sans the request for index.html naming, can we consider having the generate accept dir-name/element-name and then the entry in elements.html would just follow that path? That'd be a good start at least.

**Comment by robdodson** [comment]
I think that's the idea. I'm traveling and working on Gulp support so not sure when I'd have a chance to get to this. If you (or anyone else on the thread) is interested in throwing together a PR I can review it.

**Comment by toadkicker** [comment]
If the path is provided, do we have to still use the pattern of `el-name/el-name.html`? Is that a restriction coming from polymer, or can html imports in polymer use any naming they choose, like `foobar/baz/wath.html`?

**Comment by robdodson** [comment]
I've added a `--path` flag that you can use to define the directory structure for your element. I think wiring everything into an `index.html` is out of scope for the generator and should be easy enough for folks to do on their own.
