### ISSUE TITLE
polymer:gh fails to complete bower install

### ISSUE THREAD

**Issue by sepans** [yeoman/generator-polymer#116]
polymer:gh gives:
<pre>
bower                               ECONFLICT Unable to find suitable version for polymer
</pre>
error and exits without creating the components directory. But when I checkout the gh-pages branch and run the same command:
<pre>
bower install --config.directory="components" $org/$repo#master
</pre>
(with appropriate $org and $repo names) it works fine without asking about resolutions (the resolutions are already set in bower.json of the component).
The github repo if the element is [here](https://github.com/thelmanews/th-connector/tree/master).

Thanks

**Comment by robdodson** [comment]
@sepans is this still an issue for you with the latest generator?

**Comment by sepans** [comment]
I haven't had any issues with polymer:gh for a long time so I don't think this is still the case. I think you can close this issue. 
Thanks @robdodson.

**Comment by robdodson** [comment]
Great, glad to hear it!
