### ISSUE TITLE
bower_components moved to project root

### ISSUE THREAD

**Issue by markusgattol** [yeoman/generator-polymer#119]
currently `yo polymer` still creates `../app/bower_components` i.e. `bower_components` inside `../app` as opposed to having it in the project root, right next to `../app`, `../node_modules` etc.

http://yeoman.io/blog/bower_components-in-project-root.html

**Comment by toadkicker** [comment]
@robdodson just did a quick hack on this. Mind checking it with me and if it's good I'll send a PR over.

**Comment by robdodson** [comment]
I'd say send over the PR, that way it's easy for me to checkout and comment.
