### ISSUE TITLE
sass files not created with new web components

### ISSUE THREAD

**Issue by delebash** [yeoman/generator-polymer#120]
version 6.0

if you have chosen to use sass in your main polymer project, the sample elements come with both an scss and corresponding css file.  But when you create a new element using "yo polymer:el my-element" only a css file is created and not a corresponding scss file.

**Comment by robdodson** [comment]
ah ok I'm seeing it now. I had to switch to a different machine. Looks like the .yo-rc file isn't being written out anymore.

**Comment by delebash** [comment]
thanks!

**Comment by robdodson** [comment]
OK, found the culprit: https://github.com/yeoman/yo/issues/275

I'm going to do a patch release to downgrade back to 0.17 until this is fixed.
