### ISSUE TITLE
UnCSS

### ISSUE THREAD

**Issue by JosefJezek** [yeoman/generator-polymer#121]
Could you add UnCSS?

- https://github.com/giakki/uncss
- https://github.com/addyosmani/grunt-uncss
- http://addyosmani.com/blog/removing-unused-css/

**Comment by addyosmani** [comment]
I would suggest not using UnCSS for highly dynamic webapps like those using Polymer just yet. We have a hard enough time reliably scraping all the styles for non-Web Component apps. Doing so under the polyfills have been untested and may well not work with Shadow DOM.

**Comment by sindresorhus** [comment]
Yeah, it's already kinda fragile with just normal sites. We'll reconsider in the future when web components are more mainstream and UnCSS has been battle-tested against them.
