### ISSUE TITLE
How do you deploy the app once it's built?

### ISSUE THREAD

**Issue by mararenzsmith** [yeoman/generator-polymer#122]
Hi my app works great on local host, but I ran grunt build and then added ftp-deploy to my grunt script and ran grunt and my website did update... but to an empty page! Is there a trick to getting grunt to build a deployable version of the app that I can just upload via ftp? Or is there something more complicated that I'm missing. ( For reference, the now blank site is http://mararenzsmith.com )

**Comment by robdodson** [comment]
Looks like you got it working? Maybe you were just missing some dependencies?
