### ISSUE TITLE
Code generated by polymer:seed doesn't pass jshint with the supplied options.

### ISSUE THREAD

**Issue by pope** [yeoman/generator-polymer#123]
Here's the result from running `jshint --extract auto -e .html .`

```
x-elem.html: line 28, col 9, Missing 'new' prefix when invoking a constructor.
x-elem.html: line 61, col 9, Missing "use strict" statement.
x-elem.html: line 81, col 9, Missing "use strict" statement.

test/index.html: line 16, col NaN, 'WCT' is not defined.

test/x-elem-basic.html: line 23, col 7, Missing "use strict" statement.
test/x-elem-basic.html: line 21, col 5, 'suite' is not defined.
test/x-elem-basic.html: line 23, col 7, 'test' is not defined.
test/x-elem-basic.html: line 24, col 9, 'assert' is not defined.
test/x-elem-basic.html: line 27, col 7, 'test' is not defined.
test/x-elem-basic.html: line 28, col 9, 'assert' is not defined.
test/x-elem-basic.html: line 30, col 9, 'assert' is not defined.
test/x-elem-basic.html: line 33, col 7, 'test' is not defined.
test/x-elem-basic.html: line 35, col 11, 'assert' is not defined.

13 errors
```

This is easy to fix, but the question is are the jshint settings for external JS files only or should this apply to the embeded JS too.

**Comment by jmorille** [comment]
It could be nice to have a jshint configuration to exclude the error 
 Missing 'new' prefix when invoking a constructor.

the solution 
```
Polymer('my-custom', { // jshint ignore:line
```
is not a solution .

If you are a solution to correct this one, I will be interesting to push in the .jshintrc files.

**Comment by pope** [comment]
I believe if you set ["newcap" to false][1] then this should fix the missing 'new' prefix.

As for 'use strict', what do you think about?:

    <script>
    (function() {
      'use strict';

      Polymer('my-custom', {
        ...
      });
    })();
    </script>

[1]: http://jshint.com/docs/options/#newcap

**Comment by robdodson** [comment]
Unfortunately you can't 'use strict'.
https://github.com/yeoman/generator-polymer/issues/80

I'll remove it from jshint.
