### ISSUE TITLE
Unused code left in main application file

### ISSUE THREAD

**Issue by peterblazejewicz** [yeoman/generator-polymer#129]
There is unused code left in main application file:
https://github.com/yeoman/generator-polymer/blob/master/app/index.js#L27
```JavaScript
var defaultName = path.basename(process.cwd());
```
The application name is actually derived from built-in `determineAppname`.

Mind me removing this via PR? 
Thanks!

**Comment by robdodson** [comment]
sure!

On Tue, Jan 27, 2015 at 7:22 AM, Peter Blazejewicz <notifications@github.com
