### ISSUE TITLE
Master build generated application is broken after 2026b522

### ISSUE THREAD

**Issue by peterblazejewicz** [yeoman/generator-polymer#130]
An application generated with the current master branch is broken - this does not apply to NPM published version.
After this change:
https://github.com/yeoman/generator-polymer/commit/2026b5229e353b22129eb5cac8c1972df86d9b47
that is no longer possible to use generator linked locally via `npm link`. The Bower managed components are moved outside of `app` folder now but the build process is not yet updated at all. This breaks current master generated application's Grunt tasks, e.g.:
```
grunt build
[...]
File dist/styles/main.css created.

Running "uglify:generated" (uglify) task
>> 2 files created.

Running "vulcanize:default" (vulcanize) task
Fatal error: No input file or source string given!


Execution Time (2015-01-26 21:22:00 UTC)
```
etc.

Thanks!

**Comment by robdodson** [comment]
You should be using the released version from npm.
