### ISSUE TITLE
Make web-component-tester optional

### ISSUE THREAD

**Issue by hubgit** [yeoman/generator-polymer#131]
`web-component-tester` is useful to have in some projects, but it adds ~100MB to the project folder and takes a while to install. 

To make generation as quick and simple as possible, it would be nice to have the option not to include it when generating a new project.

**Comment by sindresorhus** [comment]
:+1:

**Comment by robdodson** [comment]
OK, I'll add this as an option following the next release. Really trying to get Gulp support wrapped up first but this should be an easy enough change after that's out.
