### ISSUE TITLE
shim-shadowdom missing after grunt build

### ISSUE THREAD

**Issue by vanxrice** [yeoman/generator-polymer#137]
My webpage imports CSS with the `shim-shadowdom` directive, when I build my project with grunt (Gruntfile.js from this generator) the `shim-shadowdom` directive is lost.

Source index.html
`<link rel="stylesheet" href="styles/main.css" shim-shadowdom>`
After `grunt build` dist/index.html
`<link rel="stylesheet" href="styles/main.css">`

I'm fairly new to Polymer, Vulcanize, and Grunt; I know the Gruntfile needs to be modified, but I'm not sure if this is a result of Vulcanization or some other step.

Any suggestions would be awesome. :smile:

**Comment by ragingwind** [comment]
I think, `usemin` task overwrite the `link` block without shim-shadowdom

**Comment by vanxrice** [comment]
I added a function to the block replacements for this case:

    usemin: {
      html: ['<%= yeoman.dist %>/{,*/}*.html'],
      css: ['<%= yeoman.dist %>/styles/{,*/}*.css'],
      options: {
        dirs: ['<%= yeoman.dist %>'],
        blockReplacements: {
          vulcanized: function (block) {
            return '<link rel="import" href="' + block.dest + '">';
          },
          css: function (block) {
            return '<link rel="stylesheet" href="' + block.dest + ' shim-shadowdom">';
          }
        }
      }
    }

I'm pretty certain this should not be default behavior, as **all** css imports get the `shim-shadowdom` attribute.

I'm closing the issue, I have a solution that works for my use case.
