### ISSUE TITLE
tests with WCT do not work / serveStatic cannot be found

### ISSUE THREAD

**Issue by Junikorn** [yeoman/generator-polymer#139]
grunt test is failing because of way .tmp is mounted in wct-test task.
Console output:

Running "wct-test:local" (wct-test) task
Could not find WCT plugin named "serveStatic"
Warning: Could not find WCT plugin named "serveStatic" Use --force to continue.

Aborted due to warnings.

**Comment by robdodson** [comment]
This should be fixed in the next release that's coming out today
