### ISSUE TITLE
Option for node-sass?

### ISSUE THREAD

**Issue by francoispluchino** [yeoman/generator-polymer#142]
It would be interesting to have an option for used [node-sass](https://www.npmjs.com/package/node-sass) instead of `sass` for developers not using Ruby.

Of course, we can do it manually, but it would be really cool to have this option directly into the generator.

Is that this feature is in your plans?

**Comment by Junikorn** [comment]
I would also add to that possibillity of choosing less if you would consider creating options for css preprocessors

**Comment by sindresorhus** [comment]
We're not going to have a LESS option, but we would be open to a node-sass option.

**Comment by robdodson** [comment]
LibSASS support was removed from a previous version because LibSass cannot compile `/deep/` combinators and that's pretty crucial for Shadow DOM CSS. https://github.com/sass/libsass/issues/452

**Comment by francoispluchino** [comment]
@robdodson Indeed, it's a problem.

I personally use `Less`, and since the [1.7.5](https://github.com/less/less.js/releases/tag/v1.7.5) version (the current version is `2.4.0`), `Less` is compatible with `/deep/`.

Perhaps more is it interesting to reconsider the use of  `Less`? Or would you remove all CSS preprocessors?

**Comment by robdodson** [comment]
@francoispluchino I think we're going to stick with Sass. RubySass compiles `/deep/` just fine, and hopefully LibSass will catch up soon.

**Comment by sp90** [comment]
@robdodson they fixed it in the latest version of libsass actually could this issue be reopened?

https://github.com/sass/libsass/issues/452

**Comment by robdodson** [comment]
@sp90 I don't think any of our templates use SASS anymore. We've switched to relying on CSS Custom Properties. I think https://github.com/StartPolymer/polymer-starter-kit-plus may use sass though
