### ISSUE TITLE
gitignore file still assumes bower components in the app directory

### ISSUE THREAD

**Issue by akc42** [yeoman/generator-polymer#144]
I just ran yo polymer with the new release and the .gitignore file generated in the root directory refers to ignoring app/bower_components.

I would have thought it should now just be bower_components, since these are off the root of the app.

**Comment by robdodson** [comment]
This was fixed: abfdb0a63a0ec830f9c566c8cda1a1b7973fca80 but it didn't make the 0.7 release. It will go out in the next update.
