### ISSUE TITLE
Many issues in gulp (mainly on windows)

### ISSUE THREAD

**Issue by oswaldomilet** [yeoman/generator-polymer#152]
I love Polymer and I am trying to use it in production projects, however my problem is not with the API itself, but with the build (generator-polymer). I have encountered so many problems (errors) from "yo polymer" in windows to dependencies missing (like ruby-sass) on mac. Need a more stable build system, cause it's discouraging my team to use Polymer and we are thinking move to angular until the boilerplate build project is solved.

**Comment by robdodson** [comment]
The dependency on Ruby Sass is going to occur if you use SASS in Polymer or Angular. You need to `gem install sass`. There's nothing we can do about that. Are there other errors that you're seeing?

**Comment by oswaldomilet** [comment]
error on gulp html...
![errorgulphtml](https://cloud.githubusercontent.com/assets/10772835/6361861/673beb1e-bc65-11e4-95b2-20ea03c5fe42.png)

**Comment by robdodson** [comment]
what happens if you run `gulp` instead of `gulp html` directly?

**Comment by oswaldomilet** [comment]
I'm so sorry, I had to install ruby and rubygems before sass (I didn't know* that, cause in mac that was not necessary). Thanks again!! (if I find more errors I'll put here ok?)

* I came from .net and now there are much things to learn in this world of webcomponents (gulp and npm dependencies are killing me).

**Comment by oswaldomilet** [comment]
![captura de tela 2015-02-25 as 13 34 13](https://cloud.githubusercontent.com/assets/10772835/6375025/2db0a02c-bcf3-11e4-9558-9f70255b44f1.png)

**Comment by oswaldomilet** [comment]
what's the incremental steps I have to do after clone a project created by yo polymer?

**Comment by oswaldomilet** [comment]
"npm update" in project folder freeze on last line in the picture
![captura de tela 2015-02-25 as 14 00 31](https://cloud.githubusercontent.com/assets/10772835/6375582/bc8264cc-bcf6-11e4-95f5-d60412c4d741.png)

**Comment by oswaldomilet** [comment]
"yo polymer" freeze on "Downloading 3.18MB"
![captura de tela 2015-02-25 as 14 12 42](https://cloud.githubusercontent.com/assets/10772835/6375929/37485688-bcf9-11e4-848b-2a08338f74be.png)

**Comment by robdodson** [comment]
Those packages can take a while to download, you may need to just be patient. The Sauce Labs stuff is big and is going to be made optional.

**Comment by oswaldomilet** [comment]
I have patience, waited about 1 hour and nothing. But ok, I installed sauce-connect-launcher separately (it was fast), then tried "yo polymer" and "npm update" and everything is fine again, thanks for your attention. I have a lot of "WARN unmet dependencies", is that a problem?

**Comment by robdodson** [comment]
no I think the warnings are ok

**Comment by oswaldomilet** [comment]
Error opening (gulp serve) on Firefox (no problems on other browsers). I guess something with browsersync...
![captura de tela 2015-02-25 as 19 30 40](https://cloud.githubusercontent.com/assets/10772835/6382137/f64c77aa-bd24-11e4-9b13-60eb45cab227.png)

**Comment by robdodson** [comment]
Hm I'm not seeing this on Mac... is this a freshly generated project?

**Comment by oswaldomilet** [comment]
Yes, it's a recent project generated with latest version of generator-polymer, however the issue not happens on initial code generated by yoman, but my project is working on other browsers (chrome, safari, IE and Opera).

**Comment by robdodson** [comment]
OK, I'm seeing the Firefox issue in a separate project that uses
BrowserSync but doesn't use the Yeoman generator. Trying to investigate if
this is just a BrowserSync problem or if webcomponents polyfills may be
negatively interacting with it.

**Comment by vhdirk** [comment]
I've just experienced the issue mentioned in comment https://github.com/yeoman/generator-polymer/issues/152#issuecomment-76075881
The problem is that browsersync will replace any <body> tag found in source files. Also those in javascript comment strings.  For me, this happened with Polymer/core-dropdown/core-dropdown.html, line 111.

**Comment by robdodson** [comment]
@vhdirk to clarify, this only happened to you in Firefox or was this also happening in other browsers?

**Comment by vhdirk** [comment]
@robdodson Yes, only Firefox (31).
In Chrome (41), everything works as expected.  I have not tested any more browsers.
