### ISSUE TITLE
Remove the files that has been vulcanized.

### ISSUE THREAD

**Issue by ragingwind** [yeoman/generator-polymer#154]
Since vulcanize, `dist/elements/elements.html` and `yo-xxx/*.*` is no more needed. It should be removed after/while for build.

**Comment by ragingwind** [comment]
Is this best solutions keeping all files under the `elements` to access to their assets? I think It would be nice that vulcanize supports removing vulcanized files.

**Comment by robdodson** [comment]
I think you may need to keep the directories incase they include things like images.

**Comment by ragingwind** [comment]
Yeah. the directories should/may be needed if it has sort of asserts. I mean that .html files vulcanized it doesn't need to be anymore. I think it would be great that vulcanize returns file list that merged its. I'll re-open the issue soon :)
