### ISSUE TITLE
BrowserSync can break in Firefox

### ISSUE THREAD

**Issue by robdodson** [yeoman/generator-polymer#156]
Need to add a --no-watch flag to the task. Probably means running a separate server.

**Comment by sindresorhus** [comment]
Can you elaborate?

**Comment by robdodson** [comment]
Related to [this comment](https://github.com/yeoman/generator-polymer/issues/152#issuecomment-76075881). I'm not able to reproduce it on a Mac with the project generated by yeoman, however, the team building the I/O website is also using BrowserSync and this error does occur for me on Mac when I run their source (it's not on GitHub yet unfortunately). They've worked around it by running a separate server if you pass a `no-watch` flag.

I haven't been able to narrow it down to an easily reproducible test case yet, which stinks. It just seems to happen sometimes with BrowserSync and FF. I'm wondering if it's possibly related to `webcomponents.js` but that's a total guess at this point.

**Comment by shakyShane** [comment]
This is a known bug, please use `reloadOnRestart: false` as a temporary fix - this will be made default in an upcoming bugfix release
