### ISSUE TITLE
label:Enhancement  - Add Coffeescript flag

### ISSUE THREAD

**Issue by caseybaggz** [yeoman/generator-polymer#158]
It would be a tasty treat if this generator came with a `--coffee` flag like other yo's do.

**Comment by robdodson** [comment]
I'm not sure all yeoman generators come with a `--coffee` flag. I don't think we're planning to add coffeescript support to the current generator but someone could add it in a fork. I'm gonna close this unless @sindresorhus or @addyosmani object.

**Comment by sindresorhus** [comment]
We're not supporting CoffeeScript in any of our generators.
