### ISSUE TITLE
Add newly created elements to test suite as well

### ISSUE THREAD

**Issue by pankajparashar** [yeoman/generator-polymer#159]
I think its a good idea to add newly created elements to the test suite, each time we create a new element using,

```sh
$ yo polymer:element my-element
```

Alongwith creating the directory structures for the new element inside the `elements` directory, we could add `my-element.html` to the `test` directory as well. 

```
.
├── test
│   ├── index.html
│   └── my-element.html
```

Additionally, the `index.html` can also be updated to include the new element,

```js
WCT.loadSuites(['yo-greeting-basic.html', 'yo-list-basic.html', 'my-element']);
```

**Comment by robdodson** [comment]
I agree! Would you be interested in putting together a PR for this?

**Comment by pankajparashar** [comment]
Yeah sure! Let me give my best shot.

**Comment by arthurvr** [comment]
@pankajparashar Did you every get to opening a PR? We're still interested :)

**Comment by robdodson** [comment]
Hey @arthurvr and @pankajparashar. I haven't talked about it much publicly but there's a big refactor of the generator coming which will be based around a starter kit that @addyosmani is building. I would suggest holding off on PRs until I get us switched over to that. Probably around end of May

**Comment by arthurvr** [comment]
@robdodson @addyosmani That's fine to me and that sounds awesome. Though you should probably have the discussions in public :)

**Comment by robdodson** [comment]
The generator has been updated now, so we can start investigating this again. I think this should hopefully be pretty easy if anyone wants to do a PR for it?

**Comment by BLamy** [comment]
@robdodson Also this.
