### ISSUE TITLE
Change cssmin to csso

### ISSUE THREAD

**Issue by ragingwind** [yeoman/generator-polymer#160]
I did't get test. However web-starter-kit, gulp-webapp generator are using `csso` to minify css. I'll change and test it If you have mind

**Comment by robdodson** [comment]
Hey @ragingwind,

I replaced `csso` with `cssmin` because `csso` can't compile `/deep/` combinators. https://github.com/yeoman/generator-polymer/pull/127#issuecomment-73013089

**Comment by ragingwind** [comment]
Sorry I forgot that :)

**Comment by robdodson** [comment]
No worries :)
