### ISSUE TITLE
Chrome apps & extensions need bower_components in app/

### ISSUE THREAD

**Issue by robdodson** [yeoman/generator-polymer#164]
Related #161 

According to @ragingwind, in order to preview Chrome apps or extensions, the bower_components directory needs to live in the app dir. This could be fixed either by passing a flag to the generator (yo polymer --chrome) that would move the bower_components dir into app and fixup the paths in the grunt or gulp files.

The element subgenerator would also need to know that this flag had been passed so it used the correct relative paths back to bower_components. This could be saved in a yo-rc file perhaps

**Comment by ragingwind** [comment]
:+1:

**Comment by arthurvr** [comment]
> in order to preview Chrome apps or extensions, the bower_components directory needs to live in the app dir. 

Yup. I don't think it can access more than that.

**Comment by robdodson** [comment]
@ragingwind would you mind moving this issue over to [Polymer Starter Kit](https://github.com/PolymerElements/polymer-starter-kit)? The generator is just pulling from there now, so that's where we would want to add in support for chrome apps.

**Comment by ragingwind** [comment]
yes I will
