### ISSUE TITLE
Uncaught TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by utnas** [yeoman/generator-polymer#165]
I't seems that the function split() is not defined on the object log "flags.log.split(",")". The error is located in the file webcomponents.js:30.

I'm using "webcomponents.js" "version": "0.5.5",

All my dependencies.
  "devDependencies": {
    "web-component-tester": "^2.2.3",
    "connect-livereload": "^0.5.2",
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^2.0.0",
    "grunt-browser-sync": "^1.9.1",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-cssmin": "^0.10.0",
    "grunt-contrib-imagemin": "^0.9.2",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-sass": "^0.8.1",
    "grunt-contrib-uglify": "^0.6.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-minify-html": "^1.1.1",
    "grunt-pagespeed": "^0.3.0",
    "grunt-replace": "^0.8.0",
    "grunt-rev": "^0.1.0",
    "grunt-usemin": "^3.0.0",
    "grunt-vulcanize": "^0.6.1",
    "jshint-stylish": "^1.0.0",
    "load-grunt-tasks": "^2.0.0",
    "serve-static": "^1.7.1",
    "time-grunt": "^1.0.0"
  },
  "engines": {
    "node": ">=0.10.0"
  }

![capture d ecran 2015-03-23 a 12 42 42 am](https://cloud.githubusercontent.com/assets/1294968/6774432/5904e80c-d0f6-11e4-9ffb-1f6fc734732e.png)
![capture d ecran 2015-03-23 a 12 43 15 am](https://cloud.githubusercontent.com/assets/1294968/6774433/5909a428-d0f6-11e4-98b4-48b7d44f11a0.png)

**Comment by robdodson** [comment]
It looks like this has recently been fixed in webcomponents.js https://github.com/webcomponents/webcomponentsjs/issues/180

**Comment by utnas** [comment]
Yes, sure it the same as #180. Thank you @robdodson
