### ISSUE TITLE
Missing brower_components out of the box

### ISSUE THREAD

**Issue by wernight** [yeoman/generator-polymer#169]
npm install yo
    npm install generator-polymer
    $(npm bin)/yo polymer
    ...
    $(npm bin)/gulp serve

Give a missing file error, similar to https://github.com/yeoman/generator-polymer/issues/13

Workaround:

    npm install bower
    $(npm bin)/bower install

**Comment by robdodson** [comment]
you have to have bower installed already, there's not much we can do about that I don't think.

**Comment by wernight** [comment]
What about installing bower locally as a dependency? May be showing an error so that I would know at the end of the install I have to run those commands?
