### ISSUE TITLE
Document how to update the gh-pages branch of a seed element

### ISSUE THREAD

**Issue by hubgit** [yeoman/generator-polymer#170]
Is the expectation that users will run `yo polymer:gh` each time there's an update, or is there an easier way to get updates from the master branch into the gh-pages branch?

**Comment by robdodson** [comment]
yes, `yo polymer:gh` will do an updated push to your gh pages branch. That's as easy as I could make it :)

**Comment by robdodson** [comment]
Sorry didn't mean to close.

**Comment by hubgit** [comment]
Fair enough - it's mildly painful having to anwer the questions from scratch each time, but not a big deal :)

I'm using [gulp and the npm gh-pages module](https://gist.github.com/hubgit/2cd2cc6334006f8e0520) for deploying Polymer apps, but there's no gulp in seed elements, so perhaps that's not an option.

**Comment by hubgit** [comment]
Thanks for closing - I should have noted that `gulp build-deploy-gh-pages` is available now.
