### ISSUE TITLE
How to hide static files from core polymer elements?

### ISSUE THREAD

**Issue by paulocheque** [yeoman/generator-polymer#177]
First of all, I am sorry by the newbie question. I am not sure if this question is related to the Polymer project.

Building my polymer elements it pratically copy all core/paper Polymer elements to _tmp folder. So they are accessed by http://localhost:3000/lib/core-icon/demo.html, bower.json etc...

Is it possible to avoid this behavior, preventing to copy at least the dev files, like demo.html?

I would not like to hide these files in my web server code.

**Comment by robdodson** [comment]
Your server shouldn't be serving the tmp dir. Only the dist dir. You can edit the grunt/gulp copy task to exclude files that you don't want.
