### ISSUE TITLE
ReferenceError: wrap is not defined

### ISSUE THREAD

**Issue by curtisblackwell** [yeoman/generator-polymer#178]
When viewing my app in Firefox, I get this error:

> ReferenceError: wrap is not defined

The [link in the comment about wrapping the document](http://www.polymer-project.org/platform/shadow-dom.html#wrappers) doesn't have that info anymore.

**Comment by curtisblackwell** [comment]
I was able to suppress the error by replacing `wrap(document)` with `document`. However, then I just got a blank screen, which I fixed by **not** using the minified HTML.

**Comment by arthurvr** [comment]
Can you be a little more specific what setup you used? Did you use gulp or grunt, for example? Did you modify anything before you ran into this issue?

> However, then I just got a blank screen, which I fixed by not using the minified HTML.

do you mean you're experiencing this issue in the `dist/` directory generated? I seem to be unable to reproduce this.

**Comment by curtisblackwell** [comment]
It seems fixing some other issues fixed this as well.

In case it still matters, I'm using Grunt and that was the built version of the code served out of the `dist` dir. Outside of a couple .js errors I was getting, I had a finished app, so I had modified a lot already.
