### ISSUE TITLE
Add support for ES6 using Babel 

### ISSUE THREAD

**Issue by thejameskyle** [yeoman/generator-polymer#181]
Happy to contibute a PR for this

**Comment by arthurvr** [comment]
I'd love to see that happening, though since we switched to polymer-starter-kit that's more topic to discuss there first, right?

In there it's difficult to make things optional though. It's a starter kit, not a Yeoman generator which you can simple give an option.

@addyosmani WDYT?

**Comment by thejameskyle** [comment]
Should I open an issue over there?

**Comment by arthurvr** [comment]
Let's wait for their feedback.

**Comment by hourliert** [comment]
I read somewhere that ES6 will be supported when ES6 will become mainstream in major browser (Not sure of the source...)... Confirmation would be great.

**Comment by addyosmani** [comment]
I'm hesitant to add tooling for ES6 to Polymer Starter Kit until the core Polymer team have a strategy for transpilation that we're happy with. We have had a ton of discussions about this in the last few months however. When we're at a happy medium, I think adding in support will make sense then.

**Comment by thejameskyle** [comment]
@addyosmani If you would like, we can schedule a google hangout sometime to discuss this stuff. We want to make sure that Babel is a good fit for everyone and that it doesn't cause people trouble.

**Comment by arthurvr** [comment]
> We have had a ton of discussions about this in the last few months however.

Any interesting stuff I can read up with? I don't remember seeing tickets about ES6 but might be totally wrong.

>  When we're at a happy medium, I think adding in support will make sense then.

Are there real technical things holding us back? If not I'd still opt to support it optionally.

**Comment by addyosmani** [comment]
@arthurvr mostly team meetings/internal discussions. Let me try to pull up a summary of notes for you this week.

**Comment by arthurvr** [comment]
@addyosmani Oh, that would be awesome, actually! Thanks! Though, **open**-source you know, try to have these discussions in public :)

**Comment by addyosmani** [comment]
We most definitely should. I've suggested all meeting notes be made public. I think we've just been short on time to tidy up/publish :)

**Comment by arthurvr** [comment]
@addyosmani Really good would be to have all discussions in a public chat/hangout (and let third-parties participate). I believe you're losing contributions this way as well. Having notes online would be a great start, though! Anyways, would love to discuss that one day, but it's not really topic for this ticket :)

**Comment by arthurvr** [comment]
> I'm hesitant to add tooling for ES6 to Polymer Starter Kit until the core Polymer team have a strategy for transpilation that we're happy with. We have had a ton of discussions about this in the last few months however. When we're at a happy medium, I think adding in support will make sense then.

So the consensus is to close this ticket for the time being?

**Comment by addyosmani** [comment]
I think so

**Comment by arlair** [comment]
It sounded like this had progressed a bit given the talk by Eric Bidelman at Polymer Summit 2015, [Using ES6 with Polymer](https://youtu.be/bX3_tN23M_Y).

I believe there were also some commits to make ES6 and Polymer integration easier.
