### ISSUE TITLE
Update it to use Polymer 1.0

### ISSUE THREAD

**Issue by Leandro-Andrade** [yeoman/generator-polymer#183]
Please update it to use the new Production version of Polymer (1.0).

Thanks

**Comment by tmess567** [comment]
Same problem here...
Please update or provide a workaround for the meantime

**Comment by tmess567** [comment]
I forked it and made changes to support it using the migrate guide...
over at https://github.com/tmess567/generator-polymer.git

This is my first work at github and polymer so please tell me if my made any mistakes

I've had some problems like styling didn't really work as expected...
I had to put inline styles to give color to the paper-toolbar element...
The font is too big... will have to change that to normal
Rest should work fine...

**Comment by arthurvr** [comment]
@robdodson @addyosmani IIRC, there was a big refactor of this generator coming up, right?

**Comment by robdodson** [comment]
Yep, id like to push it out late today if possible

**Comment by arthurvr** [comment]
Woohoo! It looks like that's all done and generator-polymer 1.0 is released! @robdodson can we close this issue?

**Comment by tmess567** [comment]
Thanks @robdodson for the quick fix...

**Comment by Leandro-Andrade** [comment]
That's awesome!
Thanks a bunch @robdodson !

I really appreciated!

**Comment by robdodson** [comment]
yep thanks guys! I'm heading out of town for a week of vacation so if there are issues I'll get on them once I return. Have a great week :)

**Comment by arthurvr** [comment]
Enjoy your vacation and thanks for the hard work!

**Comment by ragingwind** [comment]
:100: Great job and enjoy it
