### ISSUE TITLE
SASS Integration

### ISSUE THREAD

**Issue by timomeh** [yeoman/generator-polymer#187]
Is there any reason why the new refactored app- and element-generator has no SASS Integration  anymore? I really liked the choice to use scss for my elements in a separate file.

**Comment by timomeh** [comment]
I think I can answer this myself. Custom properties and variables won't work in CSS files, so a precompiler doesn't make much sense. This leaves me with the question if there's even a need for an application-wide CSS file… but this isn't related to Yeoman, so I'm going to close this.

**Comment by robdodson** [comment]
Sorry for not answering sooner, I was away on vacation. And yeah you're pretty spot on, we want to encourage the use of custom properties for styling elements. While it may not have the full blown power of SASS, it's an investment in the future that will hopefully pay off over time.

**Comment by timomeh** [comment]
Thanks for your answer – and no problem, I hope you enjoyed your vacation!
Writing CSS in HTML feels a bit strange after all these years of separating CSS from HTML, using precompilers and build-processes, but I'm sure I'll get used to it. After all Webcomponents seem to be *the* future of front end dev.

**Comment by robdodson** [comment]
@timomeh yeah it's hopefully a temporary shim until CSS custom properties are shipping in all browsers. Then we can go back to use CSS files
