### ISSUE TITLE
Answering "Yes" to  "Would you like to include an import in your elements.html file?" causes an error

### ISSUE THREAD

**Issue by lozandier** [yeoman/generator-polymer#188]
With the latest version of generator-polymer, an exception is raised when you use `"Yes"` or <kbd>Y</kbd> to answer the  `"Would you like to include an import in your elements.html file?"` prompt:
![screen shot 2015-06-04 at 9 48 23 pm](https://cloud.githubusercontent.com/assets/1223224/7997977/ba5f2742-0b03-11e5-91a1-33fcda4b79fd.png)

**Comment by timomeh** [comment]
Are you sure `/Users/lozandier/Sites/app/elements/elements.html` exists? That's the file where all your element imports are. It's generated by `yo polymer`, which scaffolds the [Polymer Starter Kit](https://github.com/polymerelements/polymer-starter-kit).

If you just use the `yo polymer:el` command and have an other project structure, this won't work.

**Comment by lozandier** [comment]
Ah thanks for clarifying that, I was running `yo polymer:el` & don't recall having to have `elements.html` defined;

I thought it would generate a `single-element` based on all the goodies added to the starter kit that's not related to making an entire app w/ Polymer or `yo polymer` being ran first. 

Thanks for clarifying that.

**Comment by robdodson** [comment]
If you want to generate a single element (outside of an app) you probably want `yo polymer:seed`. https://github.com/yeoman/generator-polymer#seed

**Comment by lozandier** [comment]
Doh! Thanks a bunch, Rob

On Sunday, June 7, 2015, Rob Dodson <notifications@github.com> wrote:

> If you want to generate a single element (outside of an app) you probably
> want yo polymer:seed. https://github.com/yeoman/generator-polymer#seed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yeoman/generator-polymer/issues/188#issuecomment-109818522>
> .
>


-- 
Kevin Lozandier
lozandier@gmail.com <lozandier@gmail.com>

**Comment by robdodson** [comment]
np!
