### ISSUE TITLE
precache.json 404

### ISSUE THREAD

**Issue by Shuunen** [yeoman/generator-polymer#190]
Hi,

I tested "gulp serve" and it worked well, then just "gulp" to build app into "dist" folder,

Then I went to dist and started here a simple "http-server" to see the result on http://localhost:8080/

The polymer app works but trigger into the console :

GET http://localhost:8080/precache.json 404 (Not Found)
Skipping precaching: unable to load precache.json

Should "precache.json" be copied from "app" folder when building ?

Ty

**Comment by robdodson** [comment]
Hey @Shuunen, the generator is just cloning [Polymer Starter Kit](https://github.com/PolymerElements/polymer-starter-kit) so you will want to raise the issue over there. I'm going to update the readme to make that more obvious.

**Comment by Shuunen** [comment]
ok :+1:

**Comment by chuckh** [comment]
@Shuunen you can try gulp serve:dist. Which will build and serve using dist.

**Comment by Shuunen** [comment]
this is weird because "gulp serve:dist" actually build but doesn't serve, it just give the same console output as if I typed "gulp"

**Comment by chuckh** [comment]
@Shuunen you should update to the latest Yeoman Generator for Polymer version 1.0.4 which includes the latest Polymer Starter Kit version 1.0.2. This may fix your problem.

You can update by going do this `npm update generator-polymer -g`

Then create a new app by doing:
- `mkdir -p my-project && cd $_`
- `yo polymer`

If you still have this problem, open a issue at https://github.com/PolymerElements/polymer-starter-kit/issues and we can continue the dialog there.
