### ISSUE TITLE
Default gulp task gives Error: EISDIR, read

### ISSUE THREAD

**Issue by bearfriend** [yeoman/generator-polymer#195]
I'm working on a polymer app (`yo polymer`), but I can't seem to run the default gulp task. I always get this error:

```` js
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EISDIR, read
````

~~I don't fully follow, but I think it may be related to https://github.com/yeoman/generator-polymer/pull/30#commitcomment-6414554~~ That's over a year old, so probably not directly related.

Anyone experienced this? Any suggestions?

---------------------
````
1.4.7
/home/dg/.nvm/v0.10.38/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/dg/npm/bin:/home/dg/bin
linux { http_parser: '1.0',
  node: '0.10.38',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.36',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1m' }
````

(No changes to gulpfile.js)

**Comment by robdodson** [comment]
Looked up this error [on StackOverflow](http://stackoverflow.com/questions/20417118/using-node-js-i-get-error-eisdir-read).

> EISDIR means that the target of the operation is a directory in reality but that the expected filetype of the target is something other than a directory.

 You may try patching in [gulp-debug](https://github.com/sindresorhus/gulp-debug) to see if you can find the failure. Or maybe run the individual gulp tasks until one breaks?  cc @addyosmani

**Comment by bearfriend** [comment]
Ok, this was related to using a symlink in my `app/` directory. The error came from the `copy` task. I had done this:

````
ln -s dir/ app/dir
````

... in order to be able to access files from the app.

It was appropriate to reverse this in my case
````
rm app/dir
mv dir/ app/ 
ln -s app/dir/ dir
````
I can probably get rid of the symlink altogether. Either way, though, getting rid of the symlink in `app/`fixed it.
