### ISSUE TITLE
how come i still got old layout with issues when installing from generator?

### ISSUE THREAD

**Issue by hazourano** [yeoman/generator-polymer#196]
still got the same issue with when a header panel resize in a large 
![screenshot from 2015-06-16 15 15 30](https://cloud.githubusercontent.com/assets/2435891/8177765/9c5c5270-143a-11e5-908a-12e27bcfd8dc.png)

i replaced with polymer-starter-kit-light-1.0.2 app directory and everything worked as expected

**Comment by arthurvr** [comment]
Chances are high you just need to update generator-polymer:

```
$ npm install --global generator-polymer
```

Only the latest relaese contains PSK 1.0.2. Let us know if you have any more troubles.

**Comment by hazourano** [comment]
I ran the command but still got the same issue

**Comment by hazourano** [comment]
after futher checking i ran this command

npm update generator-polymer -g and solved the issue

![screenshot from 2015-06-17 14 50 03](https://cloud.githubusercontent.com/assets/2435891/8201132/441bacca-1500-11e5-96fc-4a048f0435a1.png)
