### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by rchrdnsh** [yeoman/generator-polymer#198]
i set up my project and run 'gulp serve' and the app does not show up in the browser. Then I get this message in the browser: "This webpage is not available. ERR_NAME_NOT_RESOLVED. The picture goes into the details...
![screen shot 2015-06-19 at 11 17 34 am](https://cloud.githubusercontent.com/assets/7884263/8259882/d3ad9716-1674-11e5-9e1e-d0185f806d19.png)

**Comment by robdodson** [comment]
Would you mind opening this issue over on https://github.com/PolymerElements/polymer-starter-kit

The generator is just pulling directly from that project now.

**Comment by rchrdnsh** [comment]
will do :-)
