### ISSUE TITLE
node 0.12.3 install warnings

### ISSUE THREAD

**Issue by sebs** [yeoman/generator-polymer#199]
➜  grow-app git:(master) ✗ sudo npm install -g generator-polymer
Password:
npm WARN peerDependencies The peer dependency generator-mocha@>=0.1.3 included from generator-polymer will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
generator-mocha@0.1.8

**Comment by arthurvr** [comment]
See https://github.com/yeoman/yeoman/issues/1488 for the relevant discussion. One of the warnings will be gone if https://github.com/yeoman/generator-polymer/pull/200 lands.
