### ISSUE TITLE
Licence headers in template files

### ISSUE THREAD

**Issue by danhawkes** [yeoman/generator-polymer#202]
E.g. <https://github.com/yeoman/generator-polymer/blob/master/el/templates/element.html>

Are they required? It's a minor annoyance to have to delete them from the generated code each time.

**Comment by arthurvr** [comment]
Yes, they're required. It [irritates](https://github.com/PolymerElements/polymer-starter-kit/commit/c1f780a672cad04fdfd0ffd27bb5623811175f9b#commitcomment-11434133) me too. Sorry!

I'm going to leave this open to see if there really isn't a way without those but I don't believe so.

**Comment by addyosmani** [comment]
Unfortunately, any code (and therefore projects) written by Google engineers needs to include license headers. It's part of our open-source team policy :/

**Comment by arthurvr** [comment]
> Unfortunately, any code (and therefore projects) written by Google engineers needs to include license headers.

Every file? There are licensing rules in pretty much every company doing OSS but that's... :hankey: (definitely in boilerplate projects that's pretty irritating)

**Comment by addyosmani** [comment]
Almost every file. I'm trying to push for lighter restrictions on boilerplate projects because you're right - it's a PITA to have to edit them.

**Comment by arthurvr** [comment]
@addyosmani Okay. Thanks! Is there a reason in WSK only few files have license headers while in PSK almost every file has one?

**Comment by addyosmani** [comment]
I fought with the OSS team to get us the simpler setup :) Each project is considered separately though. We can go back to them and try to pitch the same level of ease as WSK for this generator and PSK. I'll try to do that over the next week or two.

**Comment by arthurvr** [comment]
Thanks!

**Comment by danhawkes** [comment]
Thanks for looking into it.
