### ISSUE TITLE
Update to PSK 1.0.3

### ISSUE THREAD

**Issue by arthurvr** [yeoman/generator-polymer#206]
Looks like @addyosmani just released PSK 1.0.3 so let's update the generator.

https://github.com/PolymerElements/polymer-starter-kit/releases/tag/v1.0.3

**Comment by robdodson** [comment]
Working on this now. I'd like to try to switch back to submodules in the short term before maybe going down the route mentioned in https://github.com/yeoman/generator-polymer/issues/205. Just need to check that the submodules get tarballed and pushed to npm properly

**Comment by arthurvr** [comment]
@robdodson This is done, isn't it?

**Comment by robdodson** [comment]
Yep, thanks for reminding me!
