### ISSUE TITLE
Full Bower Copy?

### ISSUE THREAD

**Issue by lukeed** [yeoman/generator-polymer#207]
Is it really necessary to clone everything from bower_components to dist? I thought Vulcanize was there to read true dependencies & construct a leaner concatenated deps-file?

**Comment by arthurvr** [comment]
Right from the readme:

> This generator clones Polymer Starter Kit and seed-element. If you're having issues with the template files generated for those projects, please raise them on those repos as they are the canonical source.

https://github.com/PolymerElements/polymer-starter-kit/issues/84
