### ISSUE TITLE
Add a ChromeApp generator

### ISSUE THREAD

**Issue by BrunoVernay** [yeoman/generator-polymer#210]
Not sure if `generator-polymer` should generate a ChromeApp project (using http://codingwithgerwin.blogspot.fr/2015/07/live-reload-for-polymer-chrome-apps.html and maybe https://github.com/yeoman/generator-chromeapp)

Or if `generator-chromeapp` should feature Polymer as an option ??

**Comment by robdodson** [comment]
My feeling is that generating a chrome app should be left to another generator. I'd like to keep this one as focused as possible just to reduce complexity. Closing for now, happy to discuss further if folks disagree.

**Comment by BrunoVernay** [comment]
There is hope here: https://github.com/yeoman/generator-chromeapp/issues/54
