### ISSUE TITLE
Problems with directory (bower_components)

### ISSUE THREAD

**Issue by mikkokam** [yeoman/generator-polymer#212]
OSX 10.10.3
npm 2.1.18

    npm install -g generator-polymer
    mkdir -p my-project && cd $_
    yo polymer

All OK so far.

Then

    gulp

And I get:

    ERROR finding /Users/mikkokam/Documents/git/my-project/dist/bower_components/iron-flex-layout/classes/iron-flex-layout.html

For all the imports in elements.html.

    gulp serve

And I get an empty page, plus bunch of 404's in Chrome console, all like this:

    http://localhost:3000/bower_components/webcomponentsjs/webcomponents-lite.js Failed to load resource: the server responded with a status of 404 (Not Found)

bower_components seems to be under my-project**/src**
Is this intended? It seems to be the thing that breaks everything.

**SOLUTION:**
**Option 1**
Fixed *gulpfile.js* -- there are many tasks pointing to bower_component like this:

    var bower = gulp.src([
        'bower_components/**/*'
    ]).pipe(gulp.dest('dist/bower_components'));

Replacing *'bower_components/*  with  *'src/bower_components/*  fixes most, page.js is still not found for gulp (vulcanize task).

**Option 2**
So, I ended up using a quick fix for now: 
moving *bower_components* to the top level, next to *node_modules*, and everything works out OK with no changes anywhere else.

**Comment by robdodson** [comment]
The generator doesn't create a `src` directory so I'm not sure why you're seeing that. Make sure you've got the latest version installed and try running it in a fresh directory. Also the `gulp` task creates the `dist` folder and to serve from there you'll want to run `gulp serve:dist`. When you run `gulp serve` you're serving the `app` directory. Typically you'll want to use `gulp serve` while you developer and then use `gulp` followed by `gulp serve:dist` to preview the final before you deploy.

**Comment by mikkokam** [comment]
Thanks - I checked on another computer. It did **not** add the *src* directory, thus everything works fine on that one. **So, this issue can be closed as this seems to be an issue with my Macbook.**

That one remains a mystery - *yo polymer* will always create the *src* directory and push the bower_components under that.

The difference is, I downloaded the newest **Polymer Starter Kit** and ran *npm install -g gulp bower && npm install && bower install* before installing the generator. Npm had some warnings there, so I should probably clean the installations and npm cache on the Macbook.

**Comment by robdodson** [comment]
Did you run npm install -g generator-polymer?

**Comment by mikkokam** [comment]
Yes - after PSK.

**Comment by robdodson** [comment]
You shouldn't need to download PSK to use the generator. It spits out a PSK
app for you
