### ISSUE TITLE
latest yo polymer - fails to install gruntfiles.js

### ISSUE THREAD

**Issue by gtessler24** [yeoman/generator-polymer#213]
Help

When I run yo polymer is runs w/o error. then I run GRUNT SERVER and GRUNT fails saying that it cant find gruntfile.js  and I cant see it either.

What is wrong?
Thanks

**Comment by robdodson** [comment]
The generator is now based on Polymer Starter Kit, which uses gulp.
https://github.com/yeoman/generator-polymer#issues

**Comment by gtessler24** [comment]
thank you.
what takes the place of GRUNT SERVER?
maybe polyserve?

**Comment by robdodson** [comment]
`gulp serve`.
