### ISSUE TITLE
Remove copyright header on el: generator 🔥

### ISSUE THREAD

**Issue by samccone** [yeoman/generator-polymer#217]
Not sure if I am alone on this front, but having a generator put a copyright header in my files that I have to go and delete everytime is kinda annoying.
 
https://github.com/yeoman/generator-polymer/blob/master/el/templates/element.html

Thoughts?

**Comment by robdodson** [comment]
We've been advised by our open source office to include those license headers. Technically I think deleting them violates the license (but I'm not a lawyer). I was told that if you want to license your own code you can add your own license after the Google one

Related thread: https://github.com/PolymerElements/polymer-starter-kit/issues/227

**Comment by samccone** [comment]
Thanks for the info @robdodson
