### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by shmay** [yeoman/generator-polymer#220]
I've noticed the dist output isn't doing any cache busting.  If I were to use this in production, do you foresee potential caching issues arising?  If so, any tips for implementing a cache busting solution?  Thank you.

**Comment by arthurvr** [comment]
Maybe we can document/improve these things, but this is the wrong repo. As stated in the readme please report issues with the templates at the PSK repo: https://github.com/PolymerElements/polymer-starter-kit.
