### ISSUE TITLE
Update to PSK 1.1.0

### ISSUE THREAD

**Issue by andrewebdev** [yeoman/generator-polymer#222]
App template links to an old starter kit, not the latest 1.1.0 released today :)

**Comment by arthurvr** [comment]
The version numbers of PSK and generator-polymer are independent. I do agree, though, that we have to update the templates to use PSK 1.1.0.

**Comment by robdodson** [comment]
Yep. PSK 1.1.0 was tagged while we were in Amsterdam and haven't had a
chance to catch up yet. I'm back home now and will work on this ASAP

On Tue, Sep 15, 2015 at 9:53 AM, Arthur Verschaeve <notifications@github.com

**Comment by arthurvr** [comment]
@robdodson Cool, thanks. There's no hurry ;) Hope you had a nice time in Amsterdam.

**Comment by arthurvr** [comment]
Fixed in https://github.com/yeoman/generator-polymer/commit/3f526d9e37fd1477922dce6746faa72df4e47230. @robdodson Maybe we should do a patch release too?

**Comment by robdodson** [comment]
yep working on it. Talking to Addy about whether we should stamp out the
docs/recipes folder or not. If it should be an option or a flag

On Thu, Sep 17, 2015 at 1:04 PM, Arthur Verschaeve <notifications@github.com

**Comment by arthurvr** [comment]
Optional seems like the best choice imho.
