### ISSUE TITLE
Error when generating the github page

### ISSUE THREAD

**Issue by markhuang1212** [yeoman/generator-polymer#227]
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn bash ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

by the way, my element's sourse code is [here](http://github.com/large-screen-only/large-screen-only)

**Comment by samccone** [comment]
@markhuang1212 can you list the steps to reproduce, and node version and OS please?

**Comment by markhuang1212** [comment]
I use windows 10, and my node version is 0.12.7. This happens after it asked me the name of my element. I have tried it again by creating a new element by `yo polymer:seed my-element`, but I got the same thing.

**Comment by arthurvr** [comment]
Can you give us the generator-polymer version you're on?

**Comment by ragingwind** [comment]
I would recommend that you try to re-install npm and pacakges. `Error: spawn bash ENOENT` error was related to that I saw.

**Comment by markhuang1212** [comment]
I'm using the newest version of generator-polymer. re-install npm, yeoman and polymer-generator doesn't solve the problem.

**Comment by robdodson** [comment]
Possibly dumb question as I'm not a Windows user. The line in question is trying to spawn `bash`. Will that work on Windows? Are you running any kind of bash emulation?

**Comment by markhuang1212** [comment]
@robdodson  I'm not really understand the meaning of "spawn bash" and "bash emulation". I use Git Bash sometimes, is it a kind of "bash emulation"?

**Comment by robdodson** [comment]
`bash` is the command line used on most Mac/Unix/Linux machines. This command assumes that the Node process is able to run `bash` and if it can't find it then it won't work. @addyosmani knows more about running node on Windows than I do so he might know some steps to debug. My hunch is that the node process can't find the `bash` command but I may be totally wrong, that's just a guess :)

**Comment by silentHoo** [comment]
Yep that's the problem here. The script won't run under windows. With some pain and cygwin installed it would work, but without that installed you must do the steps in the `gp.sh` by hand.

**Comment by robdodson** [comment]
@silentHoo hmmmmm any suggestions how we could make it work in both places?

**Comment by MeTaNoV** [comment]
By using 'Git Bash' it should be working, at least, it worked out for me!

**Comment by robdodson** [comment]
OK so maybe we can update the README to recommend users have Git Bash installed. That's a start at least :)

**Comment by robdodson** [comment]
Added at 3fc34f3452b62761318861fc5df0c593d989e0ed

Going to close the issue but happy to modify the underlying script if someone has a better solution

**Comment by MeTaNoV** [comment]
:+1:

**Comment by markhuang1212** [comment]
@robdodson It works when i use git bash. Thanks a lot.
