### ISSUE TITLE
Warnings during install

### ISSUE THREAD

**Issue by kishaningithub** [yeoman/generator-polymer#228]
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

**Comment by arthurvr** [comment]
That's simply a sub-dependency that had a rename. Find the package still depending on it and PR the fix there :) 

This doesn't cause any concrete problems and is not an issue with PSK so I'm closing this.
