### ISSUE TITLE
Generate gh-pages from custom branch

### ISSUE THREAD

**Issue by Zecat** [yeoman/generator-polymer#230]
Is it possible to generate gh-pages from the current or a custom branch ? In some cases it could be convenient.

**Comment by robdodson** [comment]
Right now it's hard coded to use master branch (https://github.com/yeoman/generator-polymer/blob/master/gh/index.js#L55) but that could probably be an option. `yo polymer:gh crazy-test` or something

**Comment by Zecat** [comment]
Ok thanks, this has not been implemented for a particular reason?

**Comment by robdodson** [comment]
Nobody asked until now :)

**Comment by arthurvr** [comment]
:+1:

**Comment by MeTaNoV** [comment]
+1 :)
