### ISSUE TITLE
Issue generating the project

### ISSUE THREAD

**Issue by yonathan9669** [yeoman/generator-polymer#231]
For some reason when the generator pull down the polymer-starter-kit, the .gitignore file is not pulled in the template and when the generator try to create the project throw an error.

I manually add the file and solve the issue, after try to reinstall several times in different ways the generator.

It happened when I make a clean installation of my system and install node using homebrew. So I doesn't had cache for npm when installing.

**Comment by samccone** [comment]
@yonathan9669 this is hard for us to debug unless you post the error messages / logs that you are getting.

Would you mind posting those :) 

Thx!

**Comment by robdodson** [comment]
Hm, I just fixed a small mistake from the previous version where I was copying both the `.gitignore` and `.npmignore` (https://github.com/yeoman/generator-polymer/commit/54cbf0f2fa5fb01ef83f062708a0c9b52c14fbf3) but I'm not sure if that's related to this issue. This seems like something system related. As Sam pointed out, if you can post the output from your terminal that would be helpful

**Comment by yonathan9669** [comment]
I'm sorry @samccone, i'll try to generate again the error message wiping out the entire generator package, but as I said before I fixed it manually adding the corresponding file; If @robdodson did fix a little bug related with that files probably it's already solved.  

I'll back to you with this answer.

**Comment by yonathan9669** [comment]
Well, the generator works just fine, but the latest master branch of the polymer-starter-kit project seams to have an issue.

```
[02:29:19] Finished 'elements' after 314 ms
Unhandled rejection Error: spawn ~/.../polymer-test/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:849:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
[02:29:19] styles all files 98 B
```

I already look at the repo issues and try the suggestions on PolymerElements/polymer-starter-kit#110 without any working solution.

I change my node version to 0.12.7 and back to 4.1.2 but it seams that none of them make a change to the issue.

I check and I believe it's a problem with the "optipng-bin" module because it doesn't have any vendor subfolder in it, so you should check that out.

**Comment by yonathan9669** [comment]
I made a few more test and result in a issue with the NPM, so it doesn't matter what version of node you are running it works, but the NPM version must be <= 2.14.x

This mean the issue is a recursive failure on NPM task to find the modules that the project's need.

Works great, on Node 0.12.7 & 4.1.2 but NPM must be <= 2.14.x
