### ISSUE TITLE
command not found: yo

### ISSUE THREAD

**Issue by sajjadmurtaza49** [yeoman/generator-polymer#238]
Guide me why this is appear (command not found: yo)

**Comment by ragingwind** [comment]
Did you install yo with generator-polymer? generator-polymer works with yeoman. If you're not familiar with using yeoman. please see this http://yeoman.io/learning/index.html

**Comment by sajjadmurtaza49** [comment]
i followed these step 

Install the generator npm install -g generator-polymer

Make a new directory and cd into it mkdir -p my-project && cd $_

Scaffold a new Polymer project: yo polymer

**Comment by sajjadmurtaza49** [comment]
Actually am new here for polymer.
I just started to learn polymer.

**Comment by arthurvr** [comment]
`npm i -g yo`

See yeoman.io. If that command doesn't work you have a problem with your local setup :) Not really an issue with this generator so closing.

**Comment by sajjadmurtaza49** [comment]
@ragingwind you are great :) 
Stay bless

**Comment by sajjadmurtaza49** [comment]
@ragingwind last thing - please guide
-----------------------
p_projects  mkdir -p my-project && cd $_
➜  my-project  yo polymer

     _-----_
    |       |    .--------------------------.
    |--(o)--|    | Out of the box I include |
   `---------´   |    Polymer Starter Kit   |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Would you like to include web-component-tester? Yes
? Would you like to include recipe docs? Yes
   create bower.json
   create package.json
   create LICENSE.md
   create README.md
   create app/cache-config.json
   create app/elements/elements.html
   create app/elements/my-greeting/my-greeting.html
   create app/elements/my-list/my-list.html
   create app/elements/routing.html
   create app/favicon.ico
   create app/images/touch/apple-touch-icon.png
   create app/images/touch/chrome-splashscreen-icon-384x384.png
   create app/images/touch/chrome-touch-icon-192x192.png
   create app/images/touch/icon-128x128.png
   create app/images/touch/ms-icon-144x144.png
   create app/images/touch/ms-touch-icon-144x144-precomposed.png
   create app/index.html
   create app/manifest.json
   create app/robots.txt
   create app/scripts/app.js
   create app/styles/app-theme.html
   create app/styles/main.css
   create app/styles/shared-styles.html
   create app/sw-import.js
   create .editorconfig
   create .gitattributes
   create .jscsrc
   create .jshintrc
   create .gitignore
   create gulpfile.js
   create wct.conf.js
   create app/test/index.html
   create app/test/my-greeting-basic.html
   create app/test/my-list-basic.html
   create docs/README.md
   create docs/add-es2015-support-babel.md
   create docs/chrome-dev-editor.md
   create docs/polymer-perf.md


I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN locking Error: EACCES, open '/home/sajad/.npm/_locks/glob-8eae9af10835293b.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/sajad/.npm/_locks/glob-8eae9af10835293b.lock failed { [Error: EACCES, open '/home/sajad/.npm/_locks/glob-8eae9af10835293b.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/sajad/.npm/_locks/glob-8eae9af10835293b.lock' }
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /home/sajad/p_projects/my-project/node_modules/glob, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/sajad/.npm/_locks/gulp-3813735f19375999.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/sajad/.npm/_locks/gulp-3813735f19375999.lock failed { [Error: EACCES, open '/home/sajad/.npm/_locks/gulp-3813735f19375999.lock']


Why there is ERR ? have you any idea about that.?

**Comment by ragingwind** [comment]
It's not an issue related to the generator. You can find better answer by searching on google or stackoverflow with error message hint
