### ISSUE TITLE
creating a seed element: when specifying Web Component Tester, it doesn't use <test-fixture>

### ISSUE THREAD

**Issue by akc42** [yeoman/generator-polymer#246]
When using yo Polymer:seed my-element I would have expected the generated seed-element to have been placed inside a test-fixture element for testing in the same way as when using yo Polymer:el my-element

**Comment by robdodson** [comment]
Moved to: https://github.com/PolymerElements/seed-element/issues/74

The generator just clones that project so changes should occur over there
