### ISSUE TITLE
Creating an element with Polymer:el uses the full webcomponents.js in the test files it produces

### ISSUE THREAD

**Issue by akc42** [yeoman/generator-polymer#247]
The Polymer:el script creates test html files with webcomponents.min.js script tags.

The advice here
https://www.polymer-project.org/1.0/resources/compatibility.html#polyfill-browser-support

is to only use the lite version

**Comment by robdodson** [comment]
Fixed by https://github.com/yeoman/generator-polymer/commit/e9ef7b228f76d3d9f29031a8595d32c2aabe6174
