### ISSUE TITLE
generator-polymer-plus breaks without 'node-fs-extra' and 'sugar' for me

### ISSUE THREAD

**Issue by Nejat** [yeoman/generator-polymer#250]
these two packages are listed as dev dependencies so they do not install through npm

using `yo polymer-plus` causes an `Error: Cannot find module` statement for `node-fs-extra` and `sugar`

i was able to successfully run the generator after installing both packages globally 

incidentally `yo polymer` does not have this issue

\* note - i uninstalled, cleared the cache & reinstalled the generator, before finding out these are listed are dev dependencies and the fix was to install the packages manually

* `mac os x 10.11.1`
* `node v5.1.0`
* `npm v3.5.0`

**Comment by robdodson** [comment]
What is yo polymer-plus? That's not a command we support I don't think

**Comment by Nejat** [comment]
ok thanks, i'll ignore the generator in that case. I thought it was officially support

\* fyi, it's listed as an official supported yeoman generator, listed as "by: Chrome Developer Relations" and it points back to this repository which is why I posted here.

![screen shot 2015-12-04 at 11 57 25 am](https://cloud.githubusercontent.com/assets/789809/11595595/43934372-9a7e-11e5-82cb-973b1cda7463.png)

**Comment by robdodson** [comment]
oh what the heck...

**Comment by robdodson** [comment]
cc @addyosmani
