### ISSUE TITLE
Dependancy failure gulp-minify-html and gulp-minify-css

### ISSUE THREAD

**Issue by SilverPaladin** [yeoman/generator-polymer#257]
This error is given during npm install:
```
npm WARN deprecated gulp-minify-html@1.0.5: Consider using gulp-htmlmin instead
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
```

**Comment by jsilvermist** [comment]
There already is an issue for this for Polymer Starter Kit here:
https://github.com/PolymerElements/polymer-starter-kit/issues/632
and a pull request pending testing here:
https://github.com/PolymerElements/polymer-starter-kit/pull/645

**Comment by robdodson** [comment]
Yeah, going to close this in favor of the PSK PR
