### ISSUE TITLE
Vulcanize before GitHub pages deploy

### ISSUE THREAD

**Issue by abdonrd** [yeoman/generator-polymer#259]
I think we should vulcanize before making GitHub pages deploy (`yo polymer:gh`).

**Comment by robdodson** [comment]
yeah if you're interesting in working a PR for it that would be aaaawesome

**Comment by abdonrd** [comment]
I will investigate!

**Comment by abdonrd** [comment]
@robdodson I will investigate!

**Comment by abdonrd** [comment]
@robdodson first approach: https://github.com/yeoman/generator-polymer/pull/263

**Comment by abdonrd** [comment]
Close in favor to [Polymer/polymer-cli](https://github.com/Polymer/polymer-cli)! 🎉
