### ISSUE TITLE
Update to latest version of PSK?

### ISSUE THREAD

**Issue by WaverleyDesign** [yeoman/generator-polymer#260]
This generator is getting a little outdated so far as new versions of the Polymer Starter Kit goes.. Any plans to update?

**Comment by robdodson** [comment]
We were 1 patch behind, just reved to bring us up to date. 36fe48e279d3825fe9a8f5048382ee900fab838e

**Comment by WaverleyDesign** [comment]
Cheers! That's made it all a lot easier!
