### ISSUE TITLE
Duplicate demo in gh.sh

### ISSUE THREAD

**Issue by abdonrd** [yeoman/generator-polymer#262]
In the https://github.com/yeoman/generator-polymer/blob/master/gh/templates/gp.sh#L47-L48

Why this?

``` sh
rm -rf components/$repo/demo
mv demo components/$repo/
```

Instead of this?

``` sh
rm -rf demo
```

**Comment by abdonrd** [comment]
Friendly ping to @robdodson. :)

**Comment by robdodson** [comment]
I think (but may be mistaken) that it's replacing the tagged demo with whatever one you're currently actively developing

**Comment by abdonrd** [comment]
But... It is not the same content? Previous has a `git checkout`.

**Comment by abdonrd** [comment]
Close in favor to [Polymer/polymer-cli](https://github.com/Polymer/polymer-cli)! 🎉
