### ISSUE TITLE
IronElements is gone so this is broken

### ISSUE THREAD

**Issue by stevensacks** [yeoman/generator-polymer#264]
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/PolymerElements/iron-elements.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=Operation timed out

That repo no longer exists, which means that this Yeoman generator is broken. It leaves you with an incomplete project that will not run in the browser.

Kind of a Big Deal™. :wink:

**Comment by stevensacks** [comment]
Ok I'm not sure what's going on, but I am getting weird timeout errors from github on more than just this repo. Sometimes this repo doesn't load, sometimes it's neon-elements. Not an issue, must be my network.

**Comment by samccone** [comment]
Thanks for the update and info @stevensacks :wink:

**Comment by robdodson** [comment]
I guess for anyone who comes across this issue, the iron-elements do exist here https://github.com/polymerelements/iron-elements

Possibly a github or bower issue? Might try clearing your bower cache with `bower cache clean`

**Comment by LM450N** [comment]
Using a VPN can block the download of some elements. Sometime, I have to disconnect mine. :innocent:
