### ISSUE TITLE
Syntax error in webcomponentjs on IE11 

### ISSUE THREAD

**Issue by pongsakornv** [yeoman/generator-polymer#280]
I'm not sure where to ask this... but I use this template and deploy it to tomcat server rightaway.

Chrome/FF is fine... but for IE (I use IE11) I got this error instead

SCRIPT1003: Expected ':'
File: webcomponents.js, Line: 791, Column: 11

>TreeScope.prototype = {
>      get renderer() {  //<<<< this line
>        if (this.root instanceof scope.wrappers.ShadowRoot) {

and

SCRIPT438: Object doesn't support property or method 'addEventListener'

and the result is messed up. I tried both webcomponents.js and webcomponents-lite.js and got the same result.

Thanks for helping me.

**Comment by robdodson** [comment]
Hi @pongsakornv would you mind moving the issue to github.com/webcomponents/webcomponentsjs ?
