### ISSUE TITLE
Remove `ncp`

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-polymer#35]
We should figure out the actual problem instead.

https://github.com/yeoman/generator-polymer/pull/30#commitcomment-6414554

@SBoudrias @addyosmani

**Comment by arthurvr** [comment]
We should probably just bump yeoman-generator and use all new methods anyway.

**Comment by SBoudrias** [comment]
> We should probably just bump yeoman-generator and use all new methods anyway.

:+1: that should theoretically work fine.

Why was ncp used here rather than simple copying?

**Comment by arthurvr** [comment]
> Why was ncp used here rather than simple copying?

Maybe Rob remembers. All thing I know is https://github.com/yeoman/generator-polymer/pull/30#commitcomment-6414554.

**Comment by robdodson** [comment]
@SBoudrias @arthurvr at the time using this.copy wasn't working for [this case](https://github.com/yeoman/generator-polymer/blob/176171c88f3c02f0565df71f3475b7b127e80516/gh/index.js#L50). I can bump the generator and try again to see if things have changed

**Comment by twixie** [comment]
> I can bump the generator and try again to see if things have changed

:+1:

**Comment by samccone** [comment]
@robdodson is this still an issue for you¿ :tada:

**Comment by arthurvr** [comment]
@samccone Why wouldn't it still be an issue?

> I can bump the generator and try again to see if things have changed

:+1:

**Comment by arthurvr** [comment]
(Side: bumping yeoman-generator is something that has to happen anyway.)

**Comment by samccone** [comment]
>  can bump the generator and try again to see if things have changed

`<no answer>`

So there could be a reality where it is no longer an issue.

> @samccone Why wouldn't it still be an issue?

see ^

**Comment by robdodson** [comment]
i just haven't tested it yet. got wrapped up in other things :)

**Comment by robdodson** [comment]
i'll test now

**Comment by robdodson** [comment]
ah bumping yeoman-generator makes all of the tests fail. So might need to work on this for a bit...

**Comment by arthurvr** [comment]
Yep, we had quite a bit updates since most of this generator was written.

**Comment by robdodson** [comment]
@arthurvr do you know if there is a shorter way of writing copy commands?

The previous was: `this.copy('.editorconfig', '.editorconfig')`. It seem like the new way is:

```
this.fs.copy(
 this.templatePath('.editorconfig'),
 this.destinationPath('.editorconfig')
);
```

Kinda feel like these files are going to get rather annoyingly bloated

**Comment by arthurvr** [comment]
Use globbing. In the future we'll have a better solution (https://github.com/yeoman/generator/issues/824) but globbing should work.
