### ISSUE TITLE
Sync with Web Starter Kit

### ISSUE THREAD

**Issue by trevordmiller** [yeoman/generator-polymer#52]
From Rob Dodson's request to create a ticket on [a recent Twitter conversation](https://twitter.com/rob_dodson/status/492391405411516417):

---

To match/sync with the setup of [Google's Web Starter Kit](https://developers.google.com/web/starter-kit/) and with what [Addy Osmani has been talking about](https://github.com/google/web-starter-kit/issues/229) (creating a "flavor" of the Web Starter Kit with Polymer/Web Components baked in), I would love to see/help with a few changes with this generator:

### Recommended updates to generator-polymer
- [x] Sass support / examples of using shared variables/mixins/placeholders inside of this new web component culture. Maybe also needed external links for JavaScript files and CSS files inside of each `element-name.html` file generated with `yo polymer:el element-name`?
- [x] [BrowserSync](http://addyosmani.com/blog/browser-sync/) rather than LiveReload.
- [ ] Automatic living style guide / pattern library.
- [x] PageSpeed insights.
- [x] Consistent config files/settings, like: `.jshintrc`, `.editorconfig` etc.

---

### P.S.
I just want to let the Polymer team know that you are *amazing*! Me and a few other developers at my company are working hard to adopt and push Web Components and Polymer to our fellow developers; all of your trainings/talks, hard work, updates, tools, and kindness is much appreciated. You are doing amazing work that is changing the development world.

Please let me know if you need my help with anything. I don't mean to just bring up issues here, but would like to contribute and evangelize Polymer and Web Components with my fellow developers ;)

**Comment by robdodson** [comment]
I feel like everything on the list is checked off except for the living style guide. Moving that to its own issue: https://github.com/yeoman/generator-polymer/issues/138
