### ISSUE TITLE
box-sizing: border-box

### ISSUE THREAD

**Issue by trevordmiller** [yeoman/generator-polymer#58]
To keep the generator-polymer in sync with the Google Web Starter Kit, and to follow best practices, would it be good to add the `box-sizing: border-box` setup to the general stylesheet (CSS/Sass) and/or to the `yo polymer:el` template in place of `display: block` as is currently being used?

```
html {
  box-sizing: border-box;
}
*,
*:before,
*:after {
  box-sizing: inherit;
}
```

http://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/
http://www.paulirish.com/2012/box-sizing-border-box-ftw/

**Comment by robdodson** [comment]
[Related discussion](https://github.com/PolymerLabs/seed-element/pull/41#discussion_r24836485)

**Comment by robdodson** [comment]
Closing this as the generator is now based on [Polymer Starter Kit](https://github.com/PolymerElements/polymer-starter-kit).
