### ISSUE TITLE
Add a "baked-in" example of how you would recommend overriding styles on components 

### ISSUE THREAD

**Issue by robdodson** [yeoman/generator-polymer#70]
From #68

How should this be done in a modular way? Right now I am just overriding things in main.scss with crazy selectors using /deep/ and ::shadow but this doesn't seem to be a great approach; for example:

```
// CORE TOOLBAR
trevordmiller-app::shadow core-scaffold::shadow core-scaffold::shadow core-header-panel::shadow core-toolbar::shadow {
  background: $color--primary;
}
```

or, a little better using Sass nesting:

```
html /deep/ {

  // CORE HEADER PANEL
  [main] {
    background: $color--fill;
  } // might bleed into other elements that use [main], but seems to be the only way to get it to work?

  // CORE TOOLBAR
  core-toolbar {
    background: $color--primary;
    color: $color--fill;
  }
}
```
Gross...right?

Would you recommend creating a custom component that extends the bower component and then add the styles inside of that component's stylesheet using :host instead of trying to "pierce" it from another stylesheet? For example, if I pull down core-header-panel and I want to change the default blue background color of that component, how could I do that in a modular way that reuses primary colors and styles from other components on the page?

I think people trying out web components are very confused about stuff like this...from my experience, from those that I have talked to, and from comments on articles like http://www.polymer-project.org/articles/styling-elements.html.

**Comment by delebash** [comment]
+1  I have the same questions as the OP, core-style maybe would help but even then from the examples of core-style it is still confusing and a bit of a mess.  Being able to easily theme components either from css or using sass in a structured way.  Example would be how would you recommend applying a SMACSS or other structured format to web components.  In one way web components bundle up things and make sharing code easier, but this same bundling could also make maintenance more difficult where in a SMACSS approach all styling is organized under your sass folder and sub folders, now each individual web component has its own css,scss or multiple css and scss as well as js files.

So both how do we theme components as well as how do we maintain these style sheets that cross components such as a base.scss or theme.scss.  

Rob since you are part of the Polymer team, what has the team discussed on this, haven't seen anything in the .08 primer that relates to theme and style sheet management same goes with js management.

Thanks.

**Comment by robdodson** [comment]
Much of the discussion has centered around a feature of CSS Variables called "custom properties." CSS Variables can cross the shadow boundary and they cascade. I actually used to include this in my talks on Web Components ([example](http://youtu.be/mx3YPCRNQ3A?t=26m25s)) but then Blink put CSS Variables on hold and focus shifted to `::shadow` and `/deep/`. Btw that video is super old so pretty much all of the other syntax relating to CSS in it is outdated or wrong. So only watch it for the custom properties bit!

One aspect to custom properties that we've bee talking about with the Blink team is passing "bags" or properties into an element. So instead of just setting a `font-size` you could set `font-size`, `color`, `margin`, etc., all in one fell swoop using a property bag. I guess this would be similar to Sass' mixin functionality except you wouldn't pay the cost of duplicated CSS because you'd be using actual variables.

The Polymer team is playing around with an experiment to make something that shims custom properties until support is added in Blink, but right now it's still baking, with no ETA.

So, in the short term, my thinking is any components you create can leverage SASS variables for theming. I see this working in a similar way as bootstrap. Each element has its own stylesheet and includes `_variables.scss` and `_mixins.scss`. You could combine these into a `_theme.scss` if you want. Then someone using your elements just has to override stuff in `_variables.scss` and `_mixins.scss` to theme things.

Where this gets tricky is when you have to interface with Polymer's elements. In those cases I think you'd still need to use `::shadow` and `/deep/` for the time being. Although, you could maybe make that part of your theme.

ex:

```
paper-button /deep/ #ink {
  background: @rippleColor
}
```

It's not a perfect solution but I think once we get CSS properties in place this will start to clean up nicely.

**Comment by robdodson** [comment]
Btw, I see organizing the `scss` files in the same directory as the component's html and js as a good thing. It makes the element more portable if everything is self contained and the only external part is a `_variables.scss` that lives in a sass folder

**Comment by delebash** [comment]
Thanks for the reply, its that stacking problem that gets tricky, One component that is made up of a few of my own custom components which are made up of polymer components then it gets tricky to manage the css, so deep and shadow it is for now, not a very good solution.  Css variables would fix the main problem of themeing , it would be great if the Polymer team could shim this as well, I think that would be a great solution.  Maybe after .08 release the css variables shim can be bumped up in priority as easy themeing is very important part of adopting a new framework.

Thanks again for the update, looking forward to the .08 release

**Comment by robdodson** [comment]
Yeah I think we want to get the style shimming stuff out on the heels of 0.8. Fingers crossed :)

**Comment by robdodson** [comment]
Now that the generator is using custom properties, that would be the recommended way to override or "theme" elements. https://www.polymer-project.org/1.0/docs/devguide/styling.html#xscope-styling
