### ISSUE TITLE
Add an example how to use core elements and paper elements in your app.

### ISSUE THREAD

**Issue by tonilaukka** [yeoman/generator-polymer#78]
How you should use core elements and paper elements in your app? Do you import them in index.html or in your elements html file? Say I would like to use core-header-panel and core-toolbar. Do I import them in my x-app.html or in index.html? Do I need to edit index.html or Gruntfile.js for vulcanize to work correctly?

**Comment by robdodson** [comment]
Fixed in afcda33d754a9e818bca72e0007ed77865374193
